# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - echo Creating favicon.ico from c4viz.svg
      # - convert -background none -resize 1024x1024 c4viz.svg c4viz.png
      - convert -background none -resize 256x256 c4viz.svg favicon-256.png
      - convert favicon-256.png -resize 16x16 favicon-16.png
      - convert favicon-256.png -resize 32x32 favicon-32.png
      - convert favicon-256.png -resize 64x64 favicon-64.png
      - convert favicon-256.png -resize 128x128 favicon-128.png
      - convert favicon-16.png favicon-32.png favicon-64.png favicon-128.png favicon-256.png -colors 256 favicon.ico
      - rm favicon-*.png
    silent: true
